version: '3.1'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_starter_prod
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  
  phoenix:
    # build: .
    image: alextanhongpin/phoenix
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=phoenix_starter_prod
      - DB_HOST=127.0.0.1
    ports:
      - 127.0.0.1:4000:4000